# Generated by Django 4.1.1 on 2022-10-05 17:48

from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('producto', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_stock', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
