# Generated by Django 4.1.1 on 2022-10-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProductos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoriaProductos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subcategria', models.CharField(max_length=50)),
            ],
        ),
    ]
