# Generated by Django 4.1.1 on 2022-10-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_alter_categoriaproductos_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descuento', models.IntegerField(blank=True, null=True)),
                ('fecha_caducidad', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
