# Generated by Django 4.1.1 on 2022-10-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumen',
            options={'ordering': ['titulo'], 'verbose_name': 'Resumen', 'verbose_name_plural': 'Resumenes'},
        ),
    ]
